---
- include_tasks: variables.yml

- include_tasks: RedHat.yml
  when: ansible_distribution_file_variety == 'RedHat'

- include_tasks: Debian.yml
  when: ansible_distribution_file_variety == 'Debian'

- include_tasks: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_restarted_state }}"
    enabled: "{{ postgresql_service_enabled }}"

# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml
- import_tasks: timescaledb.yml
  when: timescaledb_install
