---
- name: SELinux mode permissive
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=permissive
    create: true

- name: apply setenforce 0
  ansible.builtin.command: setenforce 0
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"
  changed_when: false
  ignore_errors: true

- name: Install packages
  yum:
    name:
        - epel-release
        - openssl
        - python3
        - python3-pip
        - python3-psycopg2
    state: present

- name: Install pip packages
  pip:
    name:
        - psycopg2-binary

- name: Install Key-repo
  rpm_key:
    key: https://download.postgresql.org/pub/repos/yum/keys/RPM-GPG-KEY-PGDG

- name: Install postgresql Repo.
  dnf:
   name: "{{ postgresql_enablerepo }}"
   state: present
   disable_gpg_check: true

- name: Disable package postgresql
  command: dnf module disable postgresql -y
  register: result
  changed_when: result.rc == 0 and 'Nothing to do' not in result.stdout

- name: PostgreSQL packages are installed.
  dnf:
    name: "{{ __postgresql_packages }}"
    state: present
  register: package_installed

- name: Check if PostgreSQL database is initialized
  stat:
    path: "{{ postgresql_data_dir }}/postgresql.conf"
  register: pgdata

- name: PostgreSQL database is initialized.
  command: "{{ postgresql_bin_path }} initdb"
  when: not pgdata.stat.exists