collections:
  - name: https://github.com/Emerson89/postgresql.git
    type: git
    version: main
  - name: community.docker
  - name: community.postgresql
    version: ">=2.0,<5.0.0"
  - name: amazon.aws
    version: "=10.3.1"
  - name: community.general
    version: ">=6.0.0,<8.0.0"
  - name: community.hashi_vault
    version: ">=4.0.0,<6.0.0"
  - name: ansible.utils
    version: ">=6.0.3"
  